### ISSUE TITLE
Create function that gets the context of each MPA + network

### ISSUE THREAD

**Issue by j-harbin** [dfo-mar-mpas/MarConsNetData#10]
We want a function that scrapes through the DFO websites and provides us with the context (size, location, etc.) of each MPA + network.

I've assigned @hallepayton to this as she is working on this now.

**Comment by hallepayton** [comment]
Done in ec2f5d140689032e319d0a509b102bd35b5f0270, 9866d5e3d3cce5cdfa7404304006aa6d43cd7129, and 3dd075e3c968b38bdef790ebc5670c3fb23217c4.
